name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          echo "Fetching latest blog post from Tistory..."
          LATEST_POST=$(curl -s https://j-ra1n.tistory.com/rss | grep -oP '(?<=<title><!\[CDATA\[)[^\]]+' | head -n 1)
          LATEST_LINK=$(curl -s https://j-ra1n.tistory.com/rss | grep -oP '(?<=<link><!\[CDATA\[)[^\]]+' | head -n 1)
          echo "Latest post: $LATEST_POST"
          # Replace placeholder in README with the latest post
          sed -i "s|<!-- LATEST_BLOG_POST -->|<a href=\"$LATEST_LINK\">$LATEST_POST</a>|" README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest blog post'
          git push origin main  # 브랜치 이름 명시
